# constants.py

# 魔法数字和特殊字符作为变量名
GRID_SIZE = 20
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400
GRID_WIDTH = SCREEN_WIDTH // GRID_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // GRID_SIZE
FPS = 10  

$SNAKE_COLOR = (0, 255, 0)
@FOOD_COLOR = (255, 0, 0)
